"""empty message

Revision ID: ad91e9f8e877
Revises: d5d832ab345f
Create Date: 2018-03-11 17:42:40.194345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad91e9f8e877'
down_revision = 'd5d832ab345f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'partysize')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('partysize', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
