"""empty message

Revision ID: d5d832ab345f
Revises: eab7d54b035a
Create Date: 2018-03-11 17:41:03.566338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d832ab345f'
down_revision = 'eab7d54b035a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('partysize', sa.Integer(), nullable=True))
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['name'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    op.drop_column('users', 'partysize')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
